server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?characterEncoding=UTF8&&serverTimezone=UTC
    username: root
    password: 1025
  redis:
    host: 192.168.150.128
    password: 1025
  rabbitmq:
    host: 192.168.150.128
    username: guest
    password: guest
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true